import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPageAuth } from '@/providers/authProviders/types'

const inter = Inter({ subsets: ['latin'] })
const Home:NextPageAuth =()=> {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        Hello
      </main>
    </>
  )
}

export default Home
